### ISSUE TITLE
Setup Bucket w/Thumbnailing for Event Cover Photos

### ISSUE THREAD

**Issue by leestanley** [acmucsd/membership-portal#108]
All images are current stored through Imgur - need to port over to s3. Need to also implement a way for [thumbnailing to reduce load size on ](https://docs.aws.amazon.com/lambda/latest/dg/with-s3-example.html)page render

Front end needs to implement lazy loading

**Comment by sumeet-bansal** [comment]
Event covers can be uploaded through the portal (to S3). Unless you mean porting over the old event covers?

**Comment by leestanley** [comment]
> Event covers can be uploaded through the portal (to S3). Unless you mean porting over the old event covers?

Yeah I meant porting over. Not sure how important it would be to keep it consistent between imgur and aws ones though

**Comment by shravanhariharan2** [comment]
Update on this - @StormFireFox1 ported over all the covers to S3, now we just need to add thumbnailing functionality

**Comment by steets250** [comment]
Frontend is going to handle the resizing.
