### ISSUE TITLE
avoid installing Postgres locally

### ISSUE THREAD

**Issue by sumeet-bansal** [acmucsd/membership-portal#11]
On Windows, setup currently requires installing Postgres locally because the `pg` Node module requires the `pg_config` executable, even though we have a Docker container for Postgres specifically to eliminate the need for local Postgres installation.

One possible avenue might be replacing the local Postgres installation's copy of `pg_config` with the Docker container's copy with a [bind mount](https://docs.docker.com/storage/bind-mounts/). Not even sure if we can use the same executable since the Postgres image might be based on alpine or debian or something, but worth looking into down the road.

Should update the README to reflect the new setup process as well.

**Comment by ronakdev** [comment]
Update: this is an issue on mac as well

**Comment by steets250** [comment]
@shravanhariharan2 let's look into this and see if removing the need for a local Postgres installation is still an issue with the backend

**Comment by trulyronak** [comment]
@shravanhariharan2 @steets250 I use the docker compose setup - I don't run postgres locally for development

just using `docker-compose up -d` / `docker-compose down` to manage it should work

**Comment by shravanhariharan2** [comment]
We've just onboarded some new devs onto the team (both on windows and mac) and they did not run into this specific issue, so I'll close this and reopen if the issue resurfaces
