### ISSUE TITLE
Portal Redesign: Feedback

### ISSUE THREAD

**Issue by shravanhariharan2** [acmucsd/membership-portal#114]
Implement the functionality for users to provide event feedback for any particular event. This feedback can include a subset of 8 feedback options, or a custom feedback if the user wants.

Implement the functionality for users to provide general ACM feedback by filling out a form and for admins to view and confirm receipt of these forms.

API Routes:
- `GET /event/:uuid` - if admin, return event feedback for a particular event along with rest of data, bucketed into feedback name and count
- `POST /event/:uuid/feedback/` - submit event feedback to a particular event (limited to 3)
- `GET /user/feedback` - get all general feedback submitted by the current user - if admin, get all general feedback by all users
- `POST /user/feedback` - submit general feedback

**Comment by sumeet-bansal** [comment]
Is the `GET /user/feedback` route necessary? I don't see it being used much.

**Comment by shravanhariharan2** [comment]
![image](https://user-images.githubusercontent.com/33337209/91520918-62088a80-e8ab-11ea-9e01-56d52fc2bfac.png)

^ I intended it on being used for this screen, where users can see all the feedback they submitted, or potentially an admin panel to view all general feedback received (like form submissions)

**Comment by sumeet-bansal** [comment]
Why reopen this?

**Comment by shravanhariharan2** [comment]
oh whoops I didn't mean to, was moving stuff around in Zenhub and I guess that triggered reopening it
