### ISSUE TITLE
Attendance API Response Naming Change

### ISSUE THREAD

**Issue by steets250** [acmucsd/membership-portal#116]
On the old API, the `/api/v1/attendance` route returned an object with the `attendance` property, but the new API returns an object with the `attendances` property. Please update the new response to match the old one. Thanks!

**Comment by shravanhariharan2** [comment]
There's a bunch of breaking changes that we have to make in the frontend (e.g. `/auth/register` -> `auth/registration` and other payload changes (see [index.ts](https://github.com/acmucsd/membership-portal/blob/typescript-rewrite/README.md))) and this is another one of them, so when I change those routes in FE I'll change this too. It's an array too so it should be plural anyway

**Comment by steets250** [comment]
@shravanhariharan2 oh, I missed that part of the readme. Are you going to make the PR for the frontend?

**Comment by shravanhariharan2** [comment]
yep I'll take care of it, should be up within next few days
