### ISSUE TITLE
Remove Banner Features

### ISSUE THREAD

**Issue by steets250** [acmucsd/membership-portal#119]
The frontend no longer uses the banner, so all code related to uploading the banner can be removed.

**Comment by sumeet-bansal** [comment]
It's not hurting anyone, so we can just leave it in there for now and revisit this issue later.

**Comment by steets250** [comment]
The banner will be used in the portal redesign, so it should be kept in the codebase.

**Comment by sumeet-bansal** [comment]
![closed](https://user-images.githubusercontent.com/29763383/117926167-2da7f380-b2ad-11eb-91a8-62040b3d7a57.jpg)
