### ISSUE TITLE
Fix database in memory cache for sliding leaderboard

### ISSUE THREAD

**Issue by shravanhariharan2** [acmucsd/membership-portal#160]
Right now, the `getLeaderboardUntil()` function returns the same payload for any from, to, offset, and limit provided. This is due to a caching issue that assigns the same unique id (undefined) to every query performed by the `getLeaderboardUntil()` function, since no id is explicitly provided. Here's a snapshot of the cache object:

![image](https://user-images.githubusercontent.com/33337209/107602837-b3999d00-6bdf-11eb-8728-b174cddd8438.png)

**Comment by sumeet-bansal** [comment]
Huh, I read somewhere that the ID would be auto-generated based on the query. If not, then maybe something like `sliding_leaderboard_${from}_${to}`?

**Comment by sumeet-bansal** [comment]
Oh, we define our own cache.

**Comment by shravanhariharan2** [comment]
Right, and [SelectQueryBuilder.cache(...)](https://github.com/typeorm/typeorm/blob/master/src/query-builder/SelectQueryBuilder.ts#L1281) doesn't assign an id if we don't give it one.

**Comment by shravanhariharan2** [comment]
Also I think `offset` and `limit` should also cache as different queries so they can return different results for the same `from` and `to`

**Comment by sumeet-bansal** [comment]
Oh oops, didn't see that you self-assigned. My b, just close the PR if you have your own.

**Comment by shravanhariharan2** [comment]
All good, its basically the same one line fix
