### ISSUE TITLE
Add 'monthlyRemaining', 'lifetimeRemaining' fields to PublicMerchItem response

### ISSUE THREAD

**Issue by shravanhariharan2** [acmucsd/membership-portal#194]
Title. This is so that Item page UI can indicate to users that they can only buy `x` more of an item for the month, or for their lifetime

**Comment by michl1001** [comment]
Only getItem route needs the modification

**Comment by steets250** [comment]
> Only get(/item/:uuid) route needs the modification

Very astute observation there, @michl1001 !
