### ISSUE TITLE
Restrict event deletion to only events that have no attendance

### ISSUE THREAD

**Issue by shravanhariharan2** [acmucsd/membership-portal#199]
It looks like currently, any event (even those that have been attended) can be deleted. This should be restricted to only those events that have no attendance since otherwise, we lose data regarding the event and the attendances (since event deletions are cascading).

https://github.com/acmucsd/membership-portal/blob/master/services/EventService.ts#L72

**Comment by sumeet-bansal** [comment]
Does the delete actually go through? I'd expect a `QueryFailedError` if a foreign key was deleted.

**Comment by shravanhariharan2** [comment]
You're right, it doesn't actually go through - `"update or delete on table \"Events\" violates foreign key constraint \"Attendances_event_Events_uuid_fkey\" on table \"Attendances\""`

So while it's technically already in place, we should still add a check for this so that the error thrown is less cryptic

**Comment by shravanhariharan2** [comment]
Also, I was mistaken above, the attendance deletion is not cascading since `onDelete: 'CASCADE'` is not enabled for the `event.attendances` field
