### ISSUE TITLE
lastLogin column of "Users" table doesn't ever get updated

### ISSUE THREAD

**Issue by shravanhariharan2** [acmucsd/membership-portal#211]
The `lastLogin` column of the "Users" table doesn't ever get updated because there's no writes to the column when a user logs in. I'm assuming that we'd want that functionality to exist in the `POST /auth/login` route, but maybe a broader discussion would be if we actually need this column or not. I'm not seeing any immediate benefits besides being able to manually audit user activity - @sumeet-bansal what are your thoughts on this?

**Comment by steets250** [comment]
Assigned to Jen
