### ISSUE TITLE
Add padding window to event checkin time

### ISSUE THREAD

**Issue by steets250** [acmucsd/membership-portal#213]
It's been requested that we allow a member to check in to an event anytime from 30 minutes before to 30 minutes after the posted time of an event. Now that events are back in person, we'd like to start enforcing that people have checked in to an event before they are allowed to enter, but if we can't start doing that until the event start time, it will lead to delays. In addition, there are cases where members may forget to check in or may not take the time to register on the portal until after the event, and we want to avoid the issue of them not having the ability to check in if that is the case. The time padding doesn't need to vary on a per-event basis, so it would be best to implement as a solely backend feature.

**Comment by shravanhariharan2** [comment]
This should be a simple edit in `POST /attendance` for checking if the event is +- 30 mins away vs. if its exactly between start and end bounds. I can make a change for this super quickly
