### ISSUE TITLE
Implement GET /order/pickup/past route

### ISSUE THREAD

**Issue by shravanhariharan2** [acmucsd/membership-portal#217]
This route should get all past pickup events, so that store managers/distributors can scroll through them and mark any orders as missed / double check orders if necessary

**Comment by shravanhariharan2** [comment]
@steets250 there might need to be some frontend design work for this route since I don't think a 'past pickup events' page has been designed yet - if you end up not seeing a need for this route then let me know. There's already a 'get all orders with filters' route so I'm not 100% sure if this route is needed yet or not.

**Comment by steets250** [comment]
@shravanhariharan2 thanks for bringing this up. I'm working on planning out what admin pages will be needed / what the flow will be, so I'll let you know soon about if we end up needing a past pickup event page or if it's unnecessary.
