### ISSUE TITLE
Send confirmation emails on order fulfillment

### ISSUE THREAD

**Issue by shravanhariharan2** [acmucsd/membership-portal#225]
Currently, only orders that are fully fulfilled have confirmation emails sent to them for users - this capability should be expanded to any type of fulfillment so that a member has confirmation after they pick up any part of their order at a pickup event, not just only if they get their full order

Edit: Wait, not even fully fulfilled orders have emails sent to them 🤔 . Updated the title accordingly

**Comment by steets250** [comment]
Description of how pickup states can go:
- if a member didn't pick up any items in their order, and their order is marked as missed, then they get an email telling them they missed it and are asked to reschedule
- if a member didn't pick up any items in their order, and their order is cancelled, then they get a full refund
- if a member picked up some items in their order, and their order is marked as missed, then they get an email telling them they picked up a few items but need to reschedule for the rest
- if a member picked up some items in their order, and their order is cancelled, then they get a partial refund
