### ISSUE TITLE
Require @ucsd.edu or @acmucsd.org emails for Merch Store Checkout

### ISSUE THREAD

**Issue by steets250** [acmucsd/membership-portal#230]
Only users with verified emails at the above domains should be able to place an order on the merch store.

**Comment by steets250** [comment]
@shravanhariharan2 thoughts on whether we should include this check in whether the user can view store entirely, or just restrict them being able to place an order? I'd lean towards the first option, as otherwise we'd need to restrict when the cart is shown and being able to add items.

**Comment by shravanhariharan2** [comment]
I think first option sounds good, that way we aren't misleading people to letting them have a look at store but not be able to purchase anything. Also emphasizes the point to that user to make sure to switch to an @ucsd.edu email
