### ISSUE TITLE
Modifying GET /order Route

### ISSUE THREAD

**Issue by steets250** [acmucsd/membership-portal#232]
The description for the `GET /order` route is currently - for a user: get all orders (and their ordered items) for that user. for an admin, get all orders (and their ordered items) by all users.

Can we modify this route so that the users orders are returned, and an admin would specifically have to indicate that they want all orders to be returned, instead of having this as the default behavior (for example, /order?all=true or something like that)? In the event that a board member who manages store wants to view their orders, I wouldn't want every single user's orders to be returned.

**Comment by shravanhariharan2** [comment]
Let's split the functionality into `GET /orders` and `GET /orders/all` so that we keep individual routes as simple as possible
