### ISSUE TITLE
Create Backend Onboarding Slides

### ISSUE THREAD

**Issue by steets250** [acmucsd/membership-portal#251]
Here's the link to creating a slide deck from the template:
https://docs.google.com/presentation/d/1iH6KejZsEdgbvQ5baed2lUf8RC3wYAB10ZLmTy3lc78/edit?usp=sharing

The goal is to give a general overview of how the backend is structured / how it works, we'll use this as an onboarding for staff / future devs.

@trulyronak feel free to add more points here

**Comment by shravanhariharan2** [comment]
Closing since presentation has finished.
