### ISSUE TITLE
Pickup events are cut off on checkout page

### ISSUE THREAD

**Issue by steets250** [acmucsd/membership-portal#261]
![unknown-15](https://user-images.githubusercontent.com/5706163/148904677-c0d5baa0-b1f4-4de1-ae6a-0b732a70134c.png)

**Comment by shravanhariharan2** [comment]
Is this a frontend or backend issue?

**Comment by steets250** [comment]
Oops, I meant to put this on frontend, but I guess I was switching back and forth on the repos 😵‍💫
