### ISSUE TITLE
Modify Duplicate Checkin Response

### ISSUE THREAD

**Issue by steets250** [acmucsd/membership-portal#300]
Can we change the response of a duplicate event checkin (currently a 400 error) so be a success such that it still indicates that the user has already checked in? There was an issue where if a member already checked in and they tried to do so again to show a board member, they had to show the error rather than the confirmation modal. Lmk if you don't think this is the right move, but hopefully this can help for events with checking confirmations.

Right now the backend returns this:
```
{
    "error": {
        "httpCode": 400,
        "message": "You have already attended this event",
        "name": "Error",
        "stack": "Error\n    at new HttpError (/app/node_modules/routing-controllers/cjs/http-error/HttpError.js:17:22)\n    at new UserError (/app/build/utils/Errors.js:7:9)\n    at AttendanceService.<anonymous> (/app/build/services/AttendanceService.js:71:27)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/build/services/AttendanceService.js:17:58)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
    }
}
```

**Comment by steets250** [comment]
Oops wrong repo

**Comment by shravanhariharan2** [comment]
We can do something like this, but would need to have some sort of distinction that this was a 'confirmation check in' vs. an actual check in (i.e. they didn't earn points on this checkin).

**Comment by steets250** [comment]
This issue will be taken care of with a frontend chance to improve user experience.
