### ISSUE TITLE
Admin Role Management

### ISSUE THREAD

**Issue by farisashai** [acmucsd/membership-portal#342]
Allow for modification of access level for any ACM account by an admin.

_Routes_
- Get all users with access type in an array.
**As an admin, you can search through a table of users and view their current `UserAccessType` from the list 
[`Restricted`, `Admin`, `Standard`, `Staff`, `Marketing`, `Merch Store Manager`, `Merch Store Distributor`].**
- Patch user access type for a specific user
**You can modify access levels of any account except other admins or promoting people to admin (must be done manually in the database)**

This feature would allow for a new precedence of people using their personal ACM portal accounts with proper permissions the way we should have been doing it always, rather then having everyone log onto the ACM Admin account (too much access and defeats the purpose of role abilities) so Marketing can only add new events, Merch distributors can only fulfill events, and members can't see any of these pages

**Comment by farisashai** [comment]
First route should be straightforward

## Update user access level
- Check if the user is an admin, if not "error: not authorized to perform this action"
- If they are an admin, confirm they're trying to modify a valid user by uuid and giving them a valid access type (that's not Admin)

**Comment by nik-dange** [comment]
@alexzhang1618 @dowhep Does the `GET` route just need to return user emails and access types, or is it necessary to return the full user info (not sure what info frontend needs/what the interface would look like)

**Comment by dowhep** [comment]
I imagine frontend just need the access types to verify the changes took effect successfully. However, given how other apis give full info all the time, we could just return the PrivateProfile of the users.
