### ISSUE TITLE
Before deploying UI V2: Rename verifyEmail to verify-email

### ISSUE THREAD

**Issue by alexzhang1618** [acmucsd/membership-portal#343]
Describe the expected behavior, e.g. "Should X, Y, and Z."
- In membership-portal-ui-v2, we've renamed the verifyEmail link that is sent to the user to verify-email instead
- We should hold off on merging this until Portal UI V2 is ready to be deployed to live

**Comment by shravanhariharan2** [comment]
Is this a backend or frontend issue? We don't have any route called verifyEmail, we only have emailVerification in the auth controller: https://github.com/acmucsd/membership-portal/blob/master/api/controllers/AuthController.ts

**Comment by shravanhariharan2** [comment]
nvm I'm assuming you're talking about the link in the register email

**Comment by shravanhariharan2** [comment]
yeah this sounds good to me then

**Comment by shravanhariharan2** [comment]
Are we changing the other client email routes to kebab case as well? Or just `verifyEmail`? If we aren't, is there a reason this route specifically is the only one that's changing from camel case to kebab case?

**Comment by alexzhang1618** [comment]
What are the other client email routes? I think we came across verifyEmail since we were working on the registration flow for portal UI V2. It's probably likely that we'll switch them to kebab case also

**Comment by shravanhariharan2** [comment]
Looks like the only other one is `/resetPassword`. Let's rename that to kebab case as well for consistency
