### ISSUE TITLE
Retroactive Attendance Response Message

### ISSUE THREAD

**Issue by farisashai** [acmucsd/membership-portal#353]
If you make a request to retroactively checkin some list of users and hit the button multiple times to send the same data, you get a success response message that the users were added successfully even if they've already checked in to the event successfully.

Instead, we should change the error message to accurately list how many users were checked in as a result of the API call - if none, "All users have already been checked in for this event" or smth like that 
 
![Screenshot 2023-05-22 at 1 06 24 AM](https://github.com/acmucsd/membership-portal/assets/33165426/baed6fa9-2e96-44f1-a43c-100bce014e86)

**Comment by dowhep** [comment]
frontend bug resolved by v2 portal
