### ISSUE TITLE
Suggestion: Sign in with Google OAuth

### ISSUE THREAD

**Issue by yeetus-skeetus** [acmucsd/membership-portal#368]
I'm a frequent event attendee and would like to share a suggestion from a user's perspective:

Instead of prompting users to create a traditional account with a password, enable sign up and sign in using a campus-issued Google account. [CSE Society](https://csesucsd.com/login) has recently implemented this.

In addition to convenience, this has additional security benefits such as eliminating the need for email verification and ensuring that the user provides their real first and last name, as UCSD Google accounts are accessed through campus Active Directory.

**Comment by SheepTester** [comment]
> real first and last name

Adding that we shouldn't really care about the names matching with the names on UCSD Google because for various personal reasons some people go by different names that aren't reflected officially on the UCSD directory

**Comment by yeetus-skeetus** [comment]
> > real first and last name
> 
> 
> 
> Adding that we shouldn't really care about the names matching with the names on UCSD Google because for various personal reasons some people go by different names that aren't reflected officially on the UCSD directory

This is a fair point! Students can always change their preferred name under Tritonlink, but a better option would be to let them change it in the portal after registering.

**Comment by alexzhang1618** [comment]
Hello! We've discussed this issue before -- here are a few reasons why we don't use Google for auth on our portal:
- like Sean mentioned above, we want to allow as much flexibility for our members to use whatever names they would like
- UCSD emails get shut down after you graduate, essentially cutting off our alumni from our website and portal
- switching to Google Authentication or even adding it would require complex migrations and refactors for our backend and database schema, and the tech debt isn't worth the benefits it may provide.

Regardless, thanks for the suggestion!
