### ISSUE TITLE
Link Events/Revamp Feedback Model & Routes

### ISSUE THREAD

**Issue by nik-dange** [acmucsd/membership-portal#386]
The feedback model currently only has "Title", "Description", and "Type" (presumably for community-specific feedback). It would be more beneficial to have feedback specifically associated with events so that we can serve a feedback form when people check in to a specific workshop, and more accurately filter feedback by event.

Permissions should remain the same (e.g., admins should be able to see all feedback, and regular members should be able to perhaps only see feedback they have submitted (for the purpose of being able to edit it)). 

It's also worth exploring a better feedback structure past the three earlier mentioned fields, such as a quicker feedback option (maybe options on a scale from Strongly Liked to Strongly Disliked) so people don't need to fill out sentences every time they want to submit feedback.

**Comment by yimmyj** [comment]
Add routes for:
Regular user: add, edit, delete feedback
Admin: get all feedback for specific event

**Comment by nik-dange** [comment]
Closed by #412
