### ISSUE TITLE
Link Discord Event ID and Google Calendar Event ID to Events

### ISSUE THREAD

**Issue by nik-dange** [acmucsd/membership-portal#413]
We're looking into building some automations for marketing so that there's a connection between the events we have on portal, Google Calendar Events, and Discord Events. This would help us move towards a world where the membership portal is more of a "hub" for events, and perhaps our automations could have us generate GCal and Discord events from the portal directly(?)

@alexzhang1618 correct me if I'm wrong on this^ or feel free to add some more clarification

We'd need to establish these columns and adjust our request types accordingly.

**Comment by alexzhang1618** [comment]
Yeah, all we need is to track the uuids of the discord event/google calendar event.

Through Portal v2 and Klefki we have the ability to generate google calendar / discord events, but have no way to edit existing ones, so having this stored though the portal would help us patch them if there are edits we need to make
