### ISSUE TITLE
implement the merch store

### ISSUE THREAD

**Issue by StoneT2000** [acmucsd/membership-portal#53]
#### /api/v1/store/item
+ [user] GET all items
+ [admin] POST a new item
+ [admin] DELETE some item(s)
+ [admin] PATCH some item(s)

#### /api/v1/store/order
+ [user] GET past orders for the current user
+ [user] POST new order to order some item(s)
+ [admin] GET past orders and unfulfilled items for a given user
+ [admin] PATCH unfulfilled order items

#### MERCHANDISE
+ id: incrementing int
+ uuid: uuid
+ item_name: string
+ price: int
+ quantity: int
+ description: string
+ discountPercentage: int

#### ORDERS
+ id: incrementing id
+ uuid: uuid
+ user: uuid
+ total_cost: int
+ ordered_at: timestamp

#### ORDER_ITEMS
+ id: incrementing id
+ order: uuid
+ item: uuid
+ fulfilled: boolean
+ fulfilled_at: timestamp

#### Misc
+ split user points into total points and spendable credits (diamonds)
+ add activity type

**Comment by sumeet-bansal** [comment]
For the API changes, +1 on the necessary routes but `/transaction` or `/order` or some other noun: REST API routes are composed of nouns (see [here](https://cloud.google.com/blog/products/api-management/restful-api-design-nouns-are-good-verbs-are-bad)).

For the database, +1 on the items table and just a single table for tracking orders.

**Comment by StoneT2000** [comment]
/transaction or /order sound better, let's go with that

sale: I think it should be a discount percent, would make frontend easier (display discount percent)

quantity: are we going to have anything that is not an int?
price: int? should it be a double/float? (or does postgres count that as double/float anyway)
