### ISSUE TITLE
Implement route rate limiting

### ISSUE THREAD

**Issue by StoneT2000** [acmucsd/membership-portal#59]
Limit the amount of requests an IP address can make to any route
Consider using https://www.npmjs.com/package/express-rate-limit

Note, we can limit some routes more than others, e.g limit password reset much more than the events route

**Comment by nalinbhardwaj** [comment]
Do you have any numbers in mind for each route? I can implement this.

**Comment by shravanhariharan2** [comment]
Closing this and reopening a new issue so that it can be resurfaced to the top of our issues list. We will be looking into rate limiting for user registration and our future "express checkin" feature shortly!

**Comment by StoneT2000** [comment]
wait when did i make this issue LMAO, what happened
